import {useState} from "react";
import type {BalanceTorqueGameSpec,FallingObjectGameSpec,FractionGroupingGameSpec,GraphMatchGameSpec,MomentumCollisionGameSpec,ProjectileGameSpec} from "../../types/game";
import {GameChrome,Slider} from "./GameChrome";
import {simulate} from "./solver/projectile";
import {simulateBalance,simulateFalling,simulateFraction,simulateGraph,simulateMomentum} from "./solver/mechanics";

const backdrop=<><rect width="800" height="430" fill="#edf3e7"/><path d="M0 370Q180 340 390 372T800 360V430H0Z" fill="#cad9ca"/><path d="M0 90h800M0 180h800M0 270h800M100 0v430M200 0v430M300 0v430M400 0v430M500 0v430M600 0v430M700 0v430" stroke="#173d2e" opacity=".07"/></>;

export function ProjectileRenderer({spec}: {spec:ProjectileGameSpec}){const [a,setA]=useState(spec.controls.angle.default),[p,setP]=useState(spec.controls.thrust.default),[result,setResult]=useState<boolean>();const check=()=>setResult(simulate(spec,a,p).hit);return <GameChrome spec={spec} won={result===true} feedback={result===undefined?undefined:result?spec.learning.explanation:"The arc missed the gate. Adjust angle or thrust."} onCheck={check} onReset={()=>{setA(spec.controls.angle.default);setP(spec.controls.thrust.default);setResult(undefined)}}><svg className="world" viewBox="0 0 800 430" role="img" aria-label="Projectile launch challenge">{backdrop}<path d={`M102 366 Q390 ${390-a*4} ${spec.physics.target_x} ${spec.physics.target_y}`} fill="none" stroke="#e8902e" strokeWidth="5" strokeDasharray="8 10"/><g transform="translate(102 366)"><circle r="23" fill="#173d2e"/><path d={`M0 0l${50*Math.cos(-a*Math.PI/180)} ${50*Math.sin(-a*Math.PI/180)}`} stroke="#173d2e" strokeWidth="14"/></g><g transform={`translate(${spec.physics.target_x} ${spec.physics.target_y})`}><circle r="42" fill="none" stroke="#e8902e" strokeWidth="9"/><circle r="10" fill="#e8902e"/></g></svg><div className="controls"><Slider label={spec.controls.angle.label} value={a} set={setA} min={20} max={65} unit="°"/><Slider label={spec.controls.thrust.label} value={p} set={setP} min={55} max={100} unit="%"/></div></GameChrome>}

export function FallingRenderer({spec}:{spec:FallingObjectGameSpec}){const [h,setH]=useState(100),[r,setR]=useState<ReturnType<typeof simulateFalling>>();const y=345-Math.min(h,800)*.34;return <GameChrome spec={spec} won={!!r?.hit} feedback={r?r.hit?spec.learning.explanation:`Measured ${r.actual.toFixed(2)} s; target ${r.target.toFixed(2)} s.`:undefined} onCheck={()=>setR(simulateFalling(spec,h))} onReset={()=>{setH(100);setR(undefined)}}><svg className="world" viewBox="0 0 800 430" role="img" aria-label="Falling object tower">{backdrop}<rect x="115" y="55" width="95" height="320" rx="8" fill="#254a3a"/><path d="M210 80h340" stroke="#173d2e" strokeDasharray="8 8"/><circle cx="560" cy={y} r="24" fill="#f6a832"/><path d={`M605 ${y}v${345-y}`} stroke="#e8902e" strokeWidth="3"/><text x="620" y={(y+345)/2} fill="#173d2e" fontSize="22">{h} m</text></svg><div className="controls"><Slider label="Drop height" value={h} set={setH} min={20} max={800} step={5} unit=" m"/></div></GameChrome>}

export function BalanceRenderer({spec}:{spec:BalanceTorqueGameSpec}){const [d,setD]=useState(2),[r,setR]=useState<ReturnType<typeof simulateBalance>>();const delta=(spec.physics.left_weight*spec.physics.left_distance-spec.physics.right_weight*d)/30;return <GameChrome spec={spec} won={!!r?.hit} feedback={r?r.hit?spec.learning.explanation:`Right torque ${r.actual.toFixed(1)}; target ${r.target.toFixed(1)}.`:undefined} onCheck={()=>setR(simulateBalance(spec,d))} onReset={()=>{setD(2);setR(undefined)}}><svg className="world" viewBox="0 0 800 430" role="img" aria-label="Torque balance beam">{backdrop}<g transform={`rotate(${Math.max(-12,Math.min(12,delta))} 400 240)`}><rect x="110" y="225" width="580" height="30" rx="15" fill="#254a3a"/><rect x={400-spec.physics.left_distance*45-35} y="160" width="70" height="65" rx="8" fill="#e8902e"/><rect x={400+d*45-35} y="175" width="70" height="50" rx="8" fill="#f6b447"/></g><path d="M400 240l-65 145h130Z" fill="#173d2e"/><text x="120" y="100" fill="#173d2e" fontSize="22">{spec.physics.left_weight} kg × {spec.physics.left_distance} m</text></svg><div className="controls"><Slider label="Right distance" value={d} set={setD} min={.5} max={10} step={.1} unit=" m"/></div></GameChrome>}

export function MomentumRenderer({spec}:{spec:MomentumCollisionGameSpec}){const [v,setV]=useState(0),[r,setR]=useState<ReturnType<typeof simulateMomentum>>();return <GameChrome spec={spec} won={!!r?.hit} feedback={r?r.hit?spec.learning.explanation:`Final velocity ${r.actual.toFixed(1)} m/s; target ${r.target.toFixed(1)} m/s.`:undefined} onCheck={()=>setR(simulateMomentum(spec,v))} onReset={()=>{setV(0);setR(undefined)}}><svg className="world" viewBox="0 0 800 430" role="img" aria-label="Momentum collision track">{backdrop}<path d="M55 325H745" stroke="#173d2e" strokeWidth="12"/><g transform={`translate(${260+v*3} 275)`}><rect width="120" height="55" rx="12" fill="#e8902e"/><circle cx="25" cy="58" r="15" fill="#173d2e"/><circle cx="95" cy="58" r="15" fill="#173d2e"/></g><g transform="translate(520 275)"><rect width="120" height="55" rx="12" fill="#254a3a"/><circle cx="25" cy="58" r="15"/><circle cx="95" cy="58" r="15"/></g><path d={`M190 230h${v*8}`} stroke="#e8902e" strokeWidth="8" markerEnd="url(#arrow)"/></svg><div className="controls"><Slider label="Player velocity" value={v} set={setV} min={-30} max={30} step={.5} unit=" m/s"/></div></GameChrome>}

export function FractionRenderer({spec}:{spec:FractionGroupingGameSpec}){const [selected,setSelected]=useState<boolean[]>(()=>Array(spec.total_items).fill(false)),[r,setR]=useState<ReturnType<typeof simulateFraction>>();const count=selected.filter(Boolean).length;return <GameChrome spec={spec} won={!!r?.hit} feedback={r?r.hit?spec.learning.explanation:`You selected ${count}; ${spec.numerator}/${spec.denominator} of ${spec.total_items} is ${r.target}.`:undefined} onCheck={()=>setR(simulateFraction(spec,count))} onReset={()=>{setSelected(Array(spec.total_items).fill(false));setR(undefined)}}><svg className="world" viewBox="0 0 800 430" role="group" aria-label={`Select ${spec.numerator}/${spec.denominator} of ${spec.total_items} items`}>{backdrop}{selected.map((on,i)=>{const x=110+(i%8)*82,y=100+Math.floor(i/8)*92;return <g key={i} role="button" tabIndex={0} aria-label={`Item ${i+1}${on?", selected":""}`} onClick={()=>setSelected(a=>a.map((x,j)=>j===i?!x:x))} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(a=>a.map((x,j)=>j===i?!x:x))}}}><circle cx={x} cy={y} r="29" fill={on?"#e8902e":"#fffdf7"} stroke="#173d2e" strokeWidth="4"/><path d={`M${x-12} ${y}h24M${x} ${y-12}v24`} stroke={on?"#fff":"#173d2e"} strokeWidth="3"/></g>})}<text x="400" y="390" textAnchor="middle" fill="#173d2e" fontSize="22">Selected {count} of {spec.total_items}</text></svg></GameChrome>}

export function GraphRenderer({spec}:{spec:GraphMatchGameSpec}){const [m,setM]=useState(0),[b,setB]=useState(0),[r,setR]=useState<ReturnType<typeof simulateGraph>>();const path=(mm:number,bb:number)=>`M80 ${215-(-5*mm+bb)*12} L720 ${215-(5*mm+bb)*12}`;return <GameChrome spec={spec} won={!!r?.hit} feedback={r?r.hit?spec.learning.explanation:`Largest parameter error: ${r.error.toFixed(2)}.`:undefined} onCheck={()=>setR(simulateGraph(spec,m,b))} onReset={()=>{setM(0);setB(0);setR(undefined)}}><svg className="world" viewBox="0 0 800 430" role="img" aria-label="Linear graph matching challenge">{backdrop}<path d="M80 215h640M400 35v360" stroke="#173d2e" strokeWidth="3"/><path d={path(spec.target_slope,spec.target_intercept)} stroke="#173d2e" strokeWidth="7" strokeDasharray="12 10"/><path d={path(m,b)} stroke="#e8902e" strokeWidth="6"/><text x="90" y="55" fill="#173d2e" fontSize="18">Dashed: target · Orange: yours</text></svg><div className="controls"><Slider label="Slope" value={m} set={setM} min={-10} max={10} step={.1} unit=""/><Slider label="Intercept" value={b} set={setB} min={-20} max={20} step={.1} unit=""/></div></GameChrome>}
