"""Render verified game specifications as isolated, self-contained HTML artifacts."""

from __future__ import annotations

import json
from html import escape

from .schemas import GameSpecV1


def render_game_html(spec: GameSpecV1) -> str:
    """Return a complete dependency-free HTML document for iframe delivery."""

    payload = json.dumps(spec.model_dump(mode="json"), separators=(",", ":")).replace("</", "<\\/")
    title = escape(spec.title)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>
:root{{--ink:#14251e;--forest:#173d2e;--paper:#f3f0e8;--surface:#fffdf7;--orange:#ef902c;--muted:#64736c;--line:#cad2cc}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:16px system-ui,-apple-system,sans-serif}}main{{min-height:100vh;display:grid;grid-template-rows:auto 1fr auto;background:var(--surface)}}header{{padding:20px 26px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;align-items:center}}header p{{margin:0 0 5px;color:var(--orange);font:700 11px ui-monospace;letter-spacing:1.5px}}h1{{font-size:24px;margin:0}}header span{{border:1px solid #75a88e;color:#286448;padding:6px 9px;font:700 9px ui-monospace}}.play{{display:grid;grid-template-columns:minmax(0,1fr) 280px;min-height:0}}canvas{{width:100%;height:100%;min-height:440px;background:#e7eee7}}aside{{padding:25px;border-left:1px solid var(--line);display:flex;flex-direction:column;gap:18px}}.concept{{color:var(--orange);font:700 10px ui-monospace;letter-spacing:1.3px}}aside h2{{font-size:24px;margin:0}}aside p{{color:var(--muted);line-height:1.55;margin:0}}.control{{display:grid;gap:8px}}.control label{{display:flex;justify-content:space-between;font-weight:700;font-size:13px}}input[type=range]{{width:100%;accent-color:var(--forest)}}.actions{{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:auto}}button{{min-height:46px;border:1px solid var(--line);background:var(--surface);font-weight:800;cursor:pointer}}button.primary{{grid-column:1/-1;background:var(--forest);color:white;border:0}}#feedback{{min-height:45px;padding:12px;background:#edf0e9;border-left:3px solid var(--orange);font-size:13px}}footer{{padding:12px 25px;border-top:1px solid var(--line);font:700 9px ui-monospace;color:var(--muted);letter-spacing:1px}}@media(max-width:760px){{.play{{grid-template-columns:1fr}}canvas{{min-height:360px}}aside{{border-left:0;border-top:1px solid var(--line)}}}}
</style></head><body><main><header><div><p id="eyebrow"></p><h1>{title}</h1></div><span>SOLVER VERIFIED</span></header><section class="play"><canvas id="world" width="900" height="520" aria-label="Interactive game canvas"></canvas><aside><span class="concept" id="concept"></span><h2 id="principle"></h2><p id="instructions"></p><div id="controls"></div><div id="feedback" role="status">Adjust the variables, then check your answer.</div><div class="actions"><button class="primary" id="check">Check answer</button><button id="hint">Hint</button><button id="reset">Replay</button></div></aside></section><footer>INTERACTIVE LEARNING · GENERATED AND VERIFIED BY PHYSICSFORGE</footer></main>
<script id="game-spec" type="application/json">{payload}</script><script>
const s=JSON.parse(document.getElementById('game-spec').textContent), values={{}};
const $=id=>document.getElementById(id), controls=$('controls'), feedback=$('feedback'), canvas=$('world'), ctx=canvas.getContext('2d');
$('eyebrow').textContent=s.eyebrow;$('concept').textContent=s.concept.toUpperCase();$('principle').textContent=s.learning.principle;$('instructions').textContent=s.instructions;
function definitions(){{switch(s.game_type){{case'projectile_target':return[["angle",s.controls.angle.label,20,65,1,s.controls.angle.default,"°"],["power",s.controls.thrust.label,55,100,1,s.controls.thrust.default,"%"]];case'falling_object':return[["height","Drop height",20,800,5,s.solution_height," m"]];case'balance_torque':return[["distance","Right distance",.5,10,.1,s.solution_right_distance," m"]];case'momentum_collision':return[["velocity","Player velocity",-30,30,.5,s.solution_player_velocity," m/s"]];case'fraction_grouping':return[["selected","Selected items",0,s.total_items,1,0," items"]];case'graph_match':return[["slope","Slope",-10,10,.1,0,""],["intercept","Intercept",-20,20,.1,0,""]]}}}}
for(const [id,label,min,max,step,value,unit] of definitions()){{values[id]=value;const box=document.createElement('div');box.className='control';box.innerHTML=`<label for="${{id}}"><span>${{label}}</span><output>${{value}}${{unit}}</output></label><input id="${{id}}" type="range" min="${{min}}" max="${{max}}" step="${{step}}" value="${{value}}">`;const input=box.querySelector('input'),out=box.querySelector('output');input.oninput=()=>{{values[id]=Number(input.value);out.textContent=input.value+unit;draw()}};controls.append(box)}}
function bg(){{ctx.fillStyle='#e7eee7';ctx.fillRect(0,0,900,520);ctx.strokeStyle='rgba(23,61,46,.09)';ctx.lineWidth=1;for(let x=0;x<900;x+=90){{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,520);ctx.stroke()}}for(let y=0;y<520;y+=86){{ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke()}}}}
function draw(){{bg();ctx.lineCap='round';ctx.font='20px system-ui';ctx.fillStyle='#173d2e';switch(s.game_type){{case'projectile_target':{{const a=values.angle*Math.PI/180,v=values.power*s.physics.thrust_scale,x0=100,y0=430;ctx.strokeStyle='#ef902c';ctx.lineWidth=5;ctx.setLineDash([9,10]);ctx.beginPath();for(let t=0;t<4;t+=.03){{const x=x0+v*Math.cos(a)*t,y=y0-(v*Math.sin(a)*t-.5*s.physics.gravity*t*t);if(t===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}}ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#173d2e';ctx.beginPath();ctx.arc(x0,y0,30,0,7);ctx.fill();ctx.strokeStyle='#ef902c';ctx.lineWidth=10;ctx.beginPath();ctx.arc(s.physics.target_x,s.physics.target_y,42,0,7);ctx.stroke();break}}case'falling_object':ctx.fillRect(110,60,100,390);ctx.fillStyle='#ef902c';ctx.beginPath();ctx.arc(600,430-Math.min(values.height,800)*.45,28,0,7);ctx.fill();ctx.fillStyle='#173d2e';ctx.fillText(values.height+' m',650,260);break;case'balance_torque':ctx.save();ctx.translate(450,290);ctx.rotate((s.physics.left_weight*s.physics.left_distance-s.physics.right_weight*values.distance)/220);ctx.fillRect(-330,-14,660,28);ctx.fillStyle='#ef902c';ctx.fillRect(-s.physics.left_distance*48-35,-85,70,70);ctx.fillRect(values.distance*48-35,-70,70,56);ctx.restore();ctx.beginPath();ctx.moveTo(450,290);ctx.lineTo(380,450);ctx.lineTo(520,450);ctx.fill();break;case'momentum_collision':ctx.fillRect(60,390,780,12);ctx.fillStyle='#ef902c';ctx.fillRect(190+values.velocity*4,320,140,70);ctx.fillStyle='#315a48';ctx.fillRect(570,320,140,70);break;case'fraction_grouping':for(let i=0;i<s.total_items;i++){{ctx.fillStyle=i<values.selected?'#ef902c':'#fffdf7';ctx.strokeStyle='#173d2e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(120+(i%8)*92,120+Math.floor(i/8)*100,30,0,7);ctx.fill();ctx.stroke()}}break;case'graph_match':ctx.strokeStyle='#173d2e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(70,260);ctx.lineTo(830,260);ctx.moveTo(450,40);ctx.lineTo(450,480);ctx.stroke();line(s.target_slope,s.target_intercept,'#173d2e',[12,9]);line(values.slope,values.intercept,'#ef902c',[]);break}}}}
function line(m,b,color,dash){{ctx.strokeStyle=color;ctx.lineWidth=6;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(70,260-(-5*m+b)*13);ctx.lineTo(830,260-(5*m+b)*13);ctx.stroke();ctx.setLineDash([])}}
function solved(){{switch(s.game_type){{case'projectile_target':{{const a=values.angle*Math.PI/180,v=values.power*s.physics.thrust_scale,tx=(s.physics.target_x-s.physics.launch_point.x)/(v*Math.cos(a)),y=s.physics.launch_point.y-(v*Math.sin(a)*tx-.5*s.physics.gravity*tx*tx);return Math.abs(y-s.physics.target_y)<=s.physics.target_tolerance}}case'falling_object':return Math.abs(values.height-s.solution_height)<=5;case'balance_torque':return Math.abs(values.distance-s.solution_right_distance)<=s.physics.torque_tolerance/Math.max(s.physics.right_weight,1);case'momentum_collision':return Math.abs(values.velocity-s.solution_player_velocity)<=s.physics.velocity_tolerance;case'fraction_grouping':return values.selected===s.solution_selected_count;case'graph_match':return Math.max(Math.abs(values.slope-s.solution_slope),Math.abs(values.intercept-s.solution_intercept))<=s.tolerance}}}}
$('check').onclick=()=>{{const win=solved();feedback.innerHTML=win?`<strong>${{s.learning.principle}}</strong><br>${{s.learning.explanation}}`:'Keep experimenting. Change a variable and try again.'}};$('hint').onclick=()=>feedback.textContent=s.learning.hint;$('reset').onclick=()=>location.reload();draw();
</script></body></html>"""
